#!/usr/bin/env bash
#
# Fitness function: commit messages follow the FDOS convention.
#
# The subject is checked mechanically. The part that actually matters — that the
# body records *why*, and states the costs accepted — cannot be checked by a
# regexp and stays a review obligation (CONTRIBUTING.md).
#
# Deliberately permissive. A hook that rejects good commits gets bypassed with
# --no-verify, and a bypassed hook enforces nothing.
#
# Two modes, for the same reason `verify-secrets.sh` has two:
#
#   message <file>   one message file, as the commit-msg hook supplies it
#   branch [base]    every commit on this branch, independent of any hook
#
# `branch` exists because the hook was the *only* thing invoking this, which
# left the convention enforced by a harness rather than by the repository. When
# that harness fails — lefthook drops the hook argument inside a linked git
# worktree (#109) — the author reaches for --no-verify and the check silently
# stops existing. `branch` is what catches that after the fact, and it is what
# makes this script reachable from `make`, which `scripts/README.md` requires of
# every script here and this one did not satisfy.
#
# # A path with spaces broke this, at two layers
#
# The commit-msg hook aborted every commit made from a linked git worktree with
# `no message file given` (#109). It was read as a lefthook defect and is not
# one.
#
# This repository lives under `/Volumes/OWC Express 1M2/…`. In the main working
# tree git passes the *relative* `.git/COMMIT_EDITMSG`, which has no spaces and
# survives any amount of unquoted interpolation. In a linked worktree it passes
# an absolute path — and `{1}` in `lefthook.yml` and `$(MSG)` in the Makefile
# were both interpolated unquoted, so the script received `/Volumes/OWC` and
# correctly reported that it was not a file.
#
# The strict failure was right the whole time. It was the diagnosis that was
# wrong, and the fix is quotes at both layers rather than a fallback here.
#
# Enforcement ladder position: automated review (rung 4), see ADR-0005.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

TYPES="feat|fix|docs|chore|refactor|test|build|perf|ci|revert"
SUBJECT_HARD_LIMIT=72
SUBJECT_GUIDELINE=50

# GitHub appends ` (#NNN)` to a squashed subject, after every check has passed.
# Measured over forty landed commits: nine exceeded 72 characters and only two
# would have without the suffix — so seven violations of this repository's own
# rule were produced by the forge, on subjects that were compliant when written
# and that nobody can now amend (#111).
#
# So an authored subject is budgeted against 72 minus the suffix. Eight
# characters covers ` (#9999)`; at five digits this becomes nine, and the check
# will say so rather than quietly start passing violations.
SUFFIX_RESERVE=8

# Character count, not byte count, and not at the mercy of the ambient locale.
#
# `${#subject}` counts characters under a UTF-8 locale and *bytes* under C. FDOS
# subjects use em dashes constantly, so the same message measures 14 on a
# developer's machine and 16 on a runner that did not set LANG — a check that
# passes locally and fails in CI, which is precisely the divergence ADR-0014
# exists to prevent. Deleting UTF-8 continuation bytes leaves one byte per
# character, portably.
char_length() {
  printf '%s' "$1" | LC_ALL=C tr -d '\200-\277' | LC_ALL=C wc -c | tr -d '[:space:]'
}

# Validates one subject line. `origin` names what is being checked, so a failure
# in branch mode says which commit rather than only what was wrong.
check_subject() {
  local subject="$1" origin="$2"

  # Merge, revert and fixup commits are generated by git, not authored.
  case "$subject" in
    Merge\ *|Revert\ *|fixup!\ *|squash!\ *) return 0 ;;
  esac

  if [ -z "$subject" ]; then
    printf 'commit-msg: empty commit message%s\n' "$origin" >&2
    return 1
  fi

  if ! printf '%s' "$subject" | grep -qE "^(${TYPES})(\([a-z0-9./-]+\))?!?: .+"; then
    printf 'commit-msg: subject must be `type(scope)?: description`%s\n' "$origin" >&2
    printf '  got:   %s\n' "$subject" >&2
    printf '  types: %s\n' "${TYPES//|/, }" >&2
    return 1
  fi

  if printf '%s' "$subject" | grep -qE '\.$'; then
    printf 'commit-msg: subject must not end with a period%s\n' "$origin" >&2
    printf '  got: %s\n' "$subject" >&2
    return 1
  fi

  local length limit landed
  length="$(char_length "$subject")"

  # A subject that already carries the suffix has landed: it is measured as it
  # is. One that does not is about to acquire one, and is measured against what
  # it will become.
  if printf '%s' "$subject" | grep -qE ' \(#[0-9]+\)$'; then
    landed=true
    limit="$SUBJECT_HARD_LIMIT"
  else
    landed=false
    limit=$((SUBJECT_HARD_LIMIT - SUFFIX_RESERVE))
  fi

  if [ "$length" -gt "$limit" ]; then
    if [ "$landed" = true ]; then
      printf 'commit-msg: subject is %d characters, limit is %d%s\n' \
        "$length" "$SUBJECT_HARD_LIMIT" "$origin" >&2
    else
      printf 'commit-msg: subject is %d characters; the limit is %d because squash\n' \
        "$length" "$limit" >&2
      printf '  merge appends " (#NNNN)" after every check has passed, and %d + %d > %d%s\n' \
        "$length" "$SUFFIX_RESERVE" "$SUBJECT_HARD_LIMIT" "$origin" >&2
    fi
    printf '  got: %s\n' "$subject" >&2
    return 1
  fi

  if [ "$length" -gt "$SUBJECT_GUIDELINE" ]; then
    printf 'commit-msg: subject is %d characters; the guideline is %d (not blocking)\n' \
      "$length" "$SUBJECT_GUIDELINE"
  fi

  return 0
}

# The first non-comment, non-blank line of a message file.
subject_of_file() {
  grep -v '^#' "$1" | sed '/^[[:space:]]*$/d' | head -1 || true
}

MODE="${1:-}"

case "$MODE" in
  message)
    MESSAGE_FILE="${2:-}"
    # Strict on purpose. A caller that passes no argument is wired wrong, and
    # rescuing it here would hide that.
    if [ -z "$MESSAGE_FILE" ] || [ ! -f "$MESSAGE_FILE" ]; then
      printf 'verify-commit-message: no message file given\n' >&2
      exit 2
    fi
    check_subject "$(subject_of_file "$MESSAGE_FILE")" ""
    ;;


  branch)
    base="${2:-}"
    if [ -z "$base" ]; then
      if git rev-parse --verify --quiet origin/main >/dev/null 2>&1; then
        base="origin/main"
      elif git rev-parse --verify --quiet main >/dev/null 2>&1; then
        base="main"
      else
        printf 'verify-commit-message: no base ref — pass one explicitly\n' >&2
        printf '  tried: origin/main, main\n' >&2
        exit 2
      fi
    fi

    printf 'Verifying commit messages (%s..HEAD)...\n' "$base"

    failures=0
    checked=0
    while IFS= read -r sha; do
      [ -n "$sha" ] || continue
      checked=$((checked + 1))
      subject="$(git log -1 --format=%s "$sha")"
      check_subject "$subject" " ($(git rev-parse --short "$sha"))" || failures=$((failures + 1))
    done < <(git rev-list "${base}..HEAD" 2>/dev/null || true)

    if [ "$failures" -gt 0 ]; then
      printf '\nFAIL: %d of %d commit message(s) violate the convention.\n' \
        "$failures" "$checked" >&2
      exit 1
    fi

    printf 'OK: %d commit message(s) valid.\n' "$checked"
    ;;

  *)
    printf 'usage: %s message <file>\n' "$0" >&2
    printf '       %s branch [base-ref]\n' "$0" >&2
    exit 2
    ;;
esac
