#!/usr/bin/env bash
#
# Fitness function: commit messages follow the FDOS convention.
#
# The subject is checked mechanically. The part that actually matters — that the
# body records *why*, and states the costs accepted — cannot be checked by a
# regexp and stays a review obligation (CONTRIBUTING.md).
#
# Deliberately permissive. A hook that rejects good commits gets bypassed with
# --no-verify, and a bypassed hook enforces nothing.
#
# Enforcement ladder position: automated review (rung 4), see ADR-0005.

set -euo pipefail

MESSAGE_FILE="${1:-}"
if [ -z "$MESSAGE_FILE" ] || [ ! -f "$MESSAGE_FILE" ]; then
  printf 'verify-commit-message: no message file given\n' >&2
  exit 2
fi

TYPES="feat|fix|docs|chore|refactor|test|build|perf|ci|revert"
SUBJECT_HARD_LIMIT=72
SUBJECT_GUIDELINE=50

subject="$(grep -v '^#' "$MESSAGE_FILE" | sed '/^[[:space:]]*$/d' | head -1 || true)"

# Merge, revert and fixup commits are generated by git, not authored.
case "$subject" in
  Merge\ *|Revert\ *|fixup!\ *|squash!\ *) exit 0 ;;
esac

if [ -z "$subject" ]; then
  printf 'commit-msg: empty commit message\n' >&2
  exit 1
fi

if ! printf '%s' "$subject" | grep -qE "^(${TYPES})(\([a-z0-9./-]+\))?!?: .+"; then
  printf 'commit-msg: subject must be `type(scope)?: description`\n' >&2
  printf '  got:   %s\n' "$subject" >&2
  printf '  types: %s\n' "${TYPES//|/, }" >&2
  exit 1
fi

if printf '%s' "$subject" | grep -qE '\.$'; then
  printf 'commit-msg: subject must not end with a period\n' >&2
  printf '  got: %s\n' "$subject" >&2
  exit 1
fi

length=${#subject}
if [ "$length" -gt "$SUBJECT_HARD_LIMIT" ]; then
  printf 'commit-msg: subject is %d characters, limit is %d\n' "$length" "$SUBJECT_HARD_LIMIT" >&2
  printf '  got: %s\n' "$subject" >&2
  exit 1
fi

if [ "$length" -gt "$SUBJECT_GUIDELINE" ]; then
  printf 'commit-msg: subject is %d characters; the guideline is %d (not blocking)\n' \
    "$length" "$SUBJECT_GUIDELINE"
fi

exit 0
