// Code generated by protoc-gen-go. DO NOT EDIT.

package kernel

import (
	"sync"
)

// Generated wire types carry serialisation tags and import sync. The rules are
// right on the substance — that is exactly why they can never be domain types
// (ADR-0018) — but nobody wrote this file, so a report could only produce a
// suppression comment. Nothing here is reported.
type Message struct {
	Name string `json:"name,omitempty"`
}

var guard sync.Mutex
